// Master wording file for the FreshBrain UI. Grouped by the area of the
// app each string belongs to; every entry carries both languages together
// so they can be reviewed side by side instead of hunting across files.

export const strings = {
  sidebar: {
    newChat: { en: 'New chat', id: 'Obrolan baru' },
    recents: { en: 'Recents', id: 'Terkini' },
    search: { en: 'Search', id: 'Cari' },
    expandSidebar: { en: 'Expand sidebar', id: 'Perluas bilah sisi' },
    closeSidebar: { en: 'Close sidebar', id: 'Tutup bilah sisi' },
    recentChats: { en: 'Recent chats', id: 'Obrolan terkini' },
    noConversations: { en: 'No conversations yet', id: 'Belum ada obrolan' },
  },
  conversationMenu: {
    options: { en: 'Conversation options', id: 'Opsi obrolan' },
    rename: { en: 'Rename', id: 'Ganti nama' },
    delete: { en: 'Delete', id: 'Hapus' },
  },
  userMenu: {
    accountMenu: { en: 'Account menu', id: 'Menu akun' },
    settings: { en: 'Settings', id: 'Pengaturan' },
    accessConfig: { en: 'Access Configuration', id: 'Konfigurasi Akses' },
    logOut: { en: 'Log out', id: 'Keluar' },
  },
  settings: {
    title: { en: 'Settings', id: 'Pengaturan' },
    close: { en: 'Close', id: 'Tutup' },
    brightness: { en: 'Brightness', id: 'Kecerahan' },
    light: { en: 'Light', id: 'Terang' },
    dark: { en: 'Dark', id: 'Gelap' },
    tone: { en: 'Tone', id: 'Nuansa' },
    cool: { en: 'Cool', id: 'Sejuk' },
    warm: { en: 'Warm', id: 'Hangat' },
    chatFont: { en: 'Chat Font', id: 'Font Chat' },
    fontSans: { en: 'Sans (Inter)', id: 'Sans (Inter)' },
    fontSerif: { en: 'Serif (Lora)', id: 'Serif (Lora)' },
    language: { en: 'Language', id: 'Bahasa' },
    languageEnglish: { en: 'English', id: 'English' },
    languageIndonesian: { en: 'Indonesia', id: 'Indonesia' },
  },
  search: {
    placeholder: { en: 'Search chats...', id: 'Cari obrolan...' },
    close: { en: 'Close search', id: 'Tutup pencarian' },
    noMatches: { en: 'No matching chats', id: 'Tidak ada obrolan yang cocok' },
  },
  chat: {
    greeting: { en: 'What would you like to know?', id: 'Apa yang ingin Anda ketahui?' },
    askPlaceholder: { en: 'Ask FreshBrain', id: 'Tanya FreshBrain' },
    sendMessage: { en: 'Send message', id: 'Kirim pesan' },
    disclaimer: {
      en: 'FreshBrain can make mistakes. Check important info.',
      id: 'FreshBrain dapat membuat kesalahan. Periksa info penting.',
    },
  },
  feedback: {
    thumbsUp: { en: 'Good response', id: 'Respons bagus' },
    thumbsDown: { en: 'Bad response', id: 'Respons kurang baik' },
    reasonPrompt: { en: 'What went wrong?', id: 'Apa yang salah?' },
    reasonWrongData: { en: "Wrong data", id: 'Data salah' },
    reasonIncomplete: { en: "Incomplete data", id: 'Data tidak lengkap' },
    reasonMisunderstood: { en: "Didn't understand my question", id: 'Tidak paham maksud saya' },
    reasonOther: { en: "Other", id: 'Lainnya' },
    commentPlaceholder: { en: 'Please provide details (optional)', id: 'Berikan detail. (opsional)' },
    submit: { en: 'Submit', id: 'Kirim' },
    cancel: { en: 'Cancel', id: 'Batal' },
  },
  auth: {
    // Always English — brand slogan, not translated.
    slogan: 'One brain. Everything fresh.',
    registerHeading: { en: 'Create your account', id: 'Buat akun Anda' },
    usernameLabel: { en: 'Username', id: 'Nama pengguna' },
    usernamePlaceholder: { en: 'Enter your username', id: 'Masukkan nama pengguna' },
    passwordLabel: { en: 'Password', id: 'Kata sandi' },
    passwordPlaceholder: { en: 'Enter your password', id: 'Masukkan kata sandi' },
    roleLabel: { en: 'Role', id: 'Peran' },
    roleCeo: { en: 'CEO', id: 'CEO' },
    roleOpsManager: { en: 'Ops Manager', id: 'Manajer Operasional' },
    roleFinance: { en: 'Finance', id: 'Keuangan' },
    roleWarehouseStaff: { en: 'Warehouse Staff', id: 'Staf Gudang' },
    roleTechnology: { en: 'Technology', id: 'Teknologi' },
    loginButton: { en: 'Log in', id: 'Masuk' },
    loginButtonLoading: { en: 'Logging in...', id: 'Sedang masuk...' },
    registerButton: { en: 'Create account', id: 'Buat akun' },
    registerButtonLoading: { en: 'Creating account...', id: 'Membuat akun...' },
    noAccount: { en: "Don't have an account?", id: 'Belum punya akun?' },
    registerLink: { en: 'Register', id: 'Daftar' },
    haveAccount: { en: 'Already have an account?', id: 'Sudah punya akun?' },
    loginLink: { en: 'Log in', id: 'Masuk' },
    usernameRequired: { en: 'Username is required', id: 'Nama pengguna wajib diisi' },
    passwordRequired: { en: 'Password is required', id: 'Kata sandi wajib diisi' },
    invalidCredentials: {
      en: 'Invalid username or password',
      id: 'Nama pengguna atau kata sandi salah',
    },
    usernameTaken: { en: 'Username already exists', id: 'Nama pengguna sudah digunakan' },
  },
  config: {
    backToChat: { en: 'Back to chat', id: 'Kembali ke obrolan' },
    title: { en: 'Access Configuration', id: 'Konfigurasi Akses' },
    navScopes: { en: 'Scopes', id: 'Cakupan' },
    navRoles: { en: 'Roles', id: 'Peran' },
    homeIntro: {
      en: "Manage which of FreshBrain's internal systems each role can query. This page only controls access — it has nothing to do with defining the tools or capabilities themselves.",
      id: 'Kelola sistem internal FreshBrain mana yang dapat diakses oleh setiap peran. Halaman ini hanya mengatur akses — tidak ada hubungannya dengan mendefinisikan tools atau kapabilitas itu sendiri.',
    },
    scopesCardTitle: { en: 'Scope catalog', id: 'Katalog cakupan' },
    scopesCardDesc: {
      en: 'Browse the full list of assignable scopes, grouped by system.',
      id: 'Telusuri daftar lengkap cakupan yang dapat diberikan, dikelompokkan per sistem.',
    },
    rolesCardTitle: { en: 'Role assignments', id: 'Penugasan peran' },
    rolesCardDesc: {
      en: 'View and edit which scopes each role is allowed to access.',
      id: 'Lihat dan ubah cakupan yang boleh diakses oleh setiap peran.',
    },
    scopesTitle: { en: 'Scope catalog', id: 'Katalog cakupan' },
    scopesDesc: {
      en: 'Read-only. The full set of scopes that can be assigned to a role, grouped by system.',
      id: 'Hanya-baca. Kumpulan lengkap cakupan yang dapat diberikan ke suatu peran, dikelompokkan per sistem.',
    },
    rolesTitle: { en: 'Role assignments', id: 'Penugasan peran' },
    rolesDesc: {
      en: 'Toggle which scopes each role can access. Changes here are local to this session and are not saved to a backend yet.',
      id: 'Aktifkan/nonaktifkan cakupan yang dapat diakses tiap peran. Perubahan di sini hanya berlaku untuk sesi ini dan belum disimpan ke backend.',
    },
    allAccess: { en: 'All access (*)', id: 'Akses penuh (*)' },
    noScopes: { en: 'No scopes assigned', id: 'Belum ada cakupan yang diberikan' },
    restricted: {
      en: "You don't have access to this page.",
      id: 'Anda tidak memiliki akses ke halaman ini.',
    },
  },
}
