// Master wording file for the FreshBrain UI. Grouped by the area of the
// app each string belongs to; every entry carries both languages together
// so they can be reviewed side by side instead of hunting across files.

export const strings = {
  sidebar: {
    newChat: { en: 'New chat', id: 'Obrolan baru' },
    recents: { en: 'Recents', id: 'Terkini' },
    search: { en: 'Search', id: 'Cari' },
    expandSidebar: { en: 'Expand sidebar', id: 'Perluas bilah sisi' },
    closeSidebar: { en: 'Close sidebar', id: 'Tutup bilah sisi' },
    recentChats: { en: 'Recent chats', id: 'Obrolan terkini' },
    noConversations: { en: 'No conversations yet', id: 'Belum ada obrolan' },
  },
  conversationMenu: {
    options: { en: 'Conversation options', id: 'Opsi obrolan' },
    rename: { en: 'Rename', id: 'Ganti nama' },
    delete: { en: 'Delete', id: 'Hapus' },
  },
  userMenu: {
    accountMenu: { en: 'Account menu', id: 'Menu akun' },
    viewProfile: { en: 'View profile', id: 'Lihat profil' },
    settings: { en: 'Settings', id: 'Pengaturan' },
    freshpedia: { en: 'Freshpedia', id: 'Freshpedia' },
    toolCatalog: { en: 'Tool Catalog', id: 'Katalog Alat' },
    accessConfig: { en: 'Access Configuration', id: 'Konfigurasi Akses' },
    logOut: { en: 'Log out', id: 'Keluar' },
  },
  profile: {
    title: { en: 'Profile', id: 'Profil' },
    close: { en: 'Close', id: 'Tutup' },
    editNotice: {
      en: 'View only. To change your name or role, ask HR.',
      id: 'Hanya lihat. Untuk mengubah nama atau peran, hubungi HR.',
    },
  },
  settings: {
    title: { en: 'Settings', id: 'Pengaturan' },
    close: { en: 'Close', id: 'Tutup' },
    brightness: { en: 'Brightness', id: 'Kecerahan' },
    light: { en: 'Light', id: 'Terang' },
    dark: { en: 'Dark', id: 'Gelap' },
    tone: { en: 'Tone', id: 'Nuansa' },
    cool: { en: 'Cool', id: 'Sejuk' },
    warm: { en: 'Warm', id: 'Hangat' },
    chatFont: { en: 'Chat Font', id: 'Font Chat' },
    fontSans: { en: 'Sans (Inter)', id: 'Sans (Inter)' },
    fontSerif: { en: 'Serif (Lora)', id: 'Serif (Lora)' },
    language: { en: 'Language', id: 'Bahasa' },
    languageEnglish: { en: 'English', id: 'English' },
    languageIndonesian: { en: 'Indonesia', id: 'Indonesia' },
  },
  search: {
    placeholder: { en: 'Search chats...', id: 'Cari obrolan...' },
    close: { en: 'Close search', id: 'Tutup pencarian' },
    noMatches: { en: 'No matching chats', id: 'Tidak ada obrolan yang cocok' },
  },
  chat: {
    greeting: { en: 'What would you like to know?', id: 'Apa yang ingin Anda ketahui?' },
    askPlaceholder: { en: 'Ask FreshBrain', id: 'Tanya FreshBrain' },
    sendMessage: { en: 'Send message', id: 'Kirim pesan' },
    disclaimer: {
      en: 'FreshBrain can make mistakes. Check important info.',
      id: 'FreshBrain dapat membuat kesalahan. Periksa info penting.',
    },
  },
  feedback: {
    thumbsUp: { en: 'Good response', id: 'Respons bagus' },
    thumbsDown: { en: 'Bad response', id: 'Respons kurang baik' },
    reasonPrompt: { en: 'What went wrong?', id: 'Apa yang salah?' },
    reasonWrongData: { en: "Wrong data", id: 'Data salah' },
    reasonIncomplete: { en: "Incomplete data", id: 'Data tidak lengkap' },
    reasonMisunderstood: { en: "Didn't understand my question", id: 'Tidak paham maksud saya' },
    reasonOther: { en: "Other", id: 'Lainnya' },
    commentPlaceholder: { en: 'Please provide details (optional)', id: 'Berikan detail. (opsional)' },
    submit: { en: 'Submit', id: 'Kirim' },
    cancel: { en: 'Cancel', id: 'Batal' },
  },
  auth: {
    // Always English — brand slogan, not translated.
    slogan: 'One brain. Everything fresh.',
    emailLabel: { en: 'Email', id: 'Email' },
    emailPlaceholder: { en: 'Enter your email', id: 'Masukkan email Anda' },
    passwordLabel: { en: 'Password', id: 'Kata sandi' },
    passwordPlaceholder: { en: 'Enter your password', id: 'Masukkan kata sandi' },
    forgotPassword: { en: 'Forgot password?', id: 'Lupa kata sandi?' },
    roleLabel: { en: 'Role', id: 'Peran' },
    roleCeo: { en: 'CEO', id: 'CEO' },
    roleOpsManager: { en: 'Ops Manager', id: 'Manajer Operasional' },
    roleFinance: { en: 'Finance', id: 'Keuangan' },
    roleWarehouseStaff: { en: 'Warehouse Staff', id: 'Staf Gudang' },
    roleTechnology: { en: 'Technology', id: 'Teknologi' },
    roleClientServiceManagement: {
      en: 'Client Service Management',
      id: 'Manajemen Layanan Klien',
    },
    roleHumanResource: { en: 'Human Resource', id: 'Sumber Daya Manusia' },
    loginButton: { en: 'Log in', id: 'Masuk' },
    loginButtonLoading: { en: 'Logging in...', id: 'Sedang masuk...' },
    emailRequired: { en: 'Email is required', id: 'Email wajib diisi' },
    passwordRequired: { en: 'Password is required', id: 'Kata sandi wajib diisi' },
    invalidCredentials: {
      en: 'Invalid email or password',
      id: 'Email atau kata sandi salah',
    },
    emailTaken: { en: 'Email already exists', id: 'Email sudah digunakan' },
  },
  config: {
    backToChat: { en: 'Back to chat', id: 'Kembali ke obrolan' },
    title: { en: 'Access Configuration', id: 'Konfigurasi Akses' },
    navScopes: { en: 'Scopes', id: 'Cakupan' },
    navRoles: { en: 'Roles', id: 'Peran' },
    navUsers: { en: 'Users', id: 'Pengguna' },
    homeIntro: {
      en: "Manage which of FreshBrain's internal systems each role can query. This page only controls access — it has nothing to do with defining the tools or capabilities themselves.",
      id: 'Kelola sistem internal FreshBrain mana yang dapat diakses oleh setiap peran. Halaman ini hanya mengatur akses — tidak ada hubungannya dengan mendefinisikan tools atau kapabilitas itu sendiri.',
    },
    scopesCardTitle: { en: 'Scope catalog', id: 'Katalog cakupan' },
    scopesCardDesc: {
      en: 'Browse the full list of assignable scopes, grouped by system.',
      id: 'Telusuri daftar lengkap cakupan yang dapat diberikan, dikelompokkan per sistem.',
    },
    rolesCardTitle: { en: 'Role assignments', id: 'Penugasan peran' },
    rolesCardDesc: {
      en: 'View and edit which scopes each role is allowed to access.',
      id: 'Lihat dan ubah cakupan yang boleh diakses oleh setiap peran.',
    },
    scopesTitle: { en: 'Scope catalog', id: 'Katalog cakupan' },
    scopesDesc: {
      en: 'Read-only. The full set of scopes that can be assigned to a role, grouped by system.',
      id: 'Hanya-baca. Kumpulan lengkap cakupan yang dapat diberikan ke suatu peran, dikelompokkan per sistem.',
    },
    rolesTitle: { en: 'Role assignments', id: 'Penugasan peran' },
    rolesDesc: {
      en: 'Toggle which scopes each role can access. Changes here are local to this session and are not saved to a backend yet.',
      id: 'Aktifkan/nonaktifkan cakupan yang dapat diakses tiap peran. Perubahan di sini hanya berlaku untuk sesi ini dan belum disimpan ke backend.',
    },
    allAccess: { en: 'All access (*)', id: 'Akses penuh (*)' },
    noScopes: { en: 'No scopes assigned', id: 'Belum ada cakupan yang diberikan' },
    restricted: {
      en: "You don't have access to this page.",
      id: 'Anda tidak memiliki akses ke halaman ini.',
    },
    usersCardTitle: { en: 'Users', id: 'Pengguna' },
    usersCardDesc: {
      en: 'Add users and manage their name and role.',
      id: 'Tambahkan pengguna dan kelola nama serta peran mereka.',
    },
    usersTitle: { en: 'Users', id: 'Pengguna' },
    usersDesc: {
      en: 'Add users and edit their name or role. Changes here are local to this session and are not saved to a backend yet.',
      id: 'Tambahkan pengguna dan ubah nama atau peran mereka. Perubahan di sini hanya berlaku untuk sesi ini dan belum disimpan ke backend.',
    },
    nameLabel: { en: 'Name', id: 'Nama' },
    namePlaceholder: { en: 'Full name', id: 'Nama lengkap' },
    searchUsersPlaceholder: {
      en: 'Search by name, email, or phone…',
      id: 'Cari berdasarkan nama, email, atau telepon…',
    },
    filterByRoleLabel: { en: 'Filter by role', id: 'Filter berdasarkan peran' },
    emailPlaceholder: { en: 'name@company.com', id: 'nama@perusahaan.com' },
    phoneLabel: { en: 'Phone', id: 'Telepon' },
    phonePlaceholder: { en: '+62 812-3456-7890', id: '+62 812-3456-7890' },
    addUser: { en: 'Add user', id: 'Tambah pengguna' },
    addUserSubmit: { en: 'Add', id: 'Tambahkan' },
    editUser: { en: 'Edit', id: 'Ubah' },
    saveUser: { en: 'Save', id: 'Simpan' },
    cancelEdit: { en: 'Cancel', id: 'Batal' },
    close: { en: 'Close', id: 'Tutup' },
    viewOnlyNotice: {
      en: "View only. You don't have permission to make changes here.",
      id: 'Hanya lihat. Anda tidak memiliki izin untuk mengubah data di sini.',
    },
    resetLinkLabel: {
      en: 'Reset link (share with the user manually):',
      id: 'Tautan reset (bagikan ke pengguna secara manual):',
    },
    copyLink: { en: 'Copy', id: 'Salin' },
    copied: { en: 'Copied', id: 'Tersalin' },
  },
  permissions: {
    sectionLabel: { en: 'Permissions', id: 'Izin' },
    accessConfigSectionLabel: { en: 'Access Config', id: 'Konfigurasi Akses' },
    userManagementSectionLabel: { en: 'User Management', id: 'Manajemen Pengguna' },
    chatAccessSectionLabel: { en: 'Chat Access', id: 'Akses Chat' },

    usersView: { en: 'Users — View', id: 'Pengguna — Lihat' },
    usersEdit: { en: 'Users — Edit', id: 'Pengguna — Ubah' },

    configScopesView: { en: 'Scopes — View', id: 'Cakupan — Lihat' },
    configRolesView: { en: 'Roles — View', id: 'Peran — Lihat' },
    configRolesEdit: { en: 'Roles — Edit', id: 'Peran — Ubah' },
    configAccessPermissionEdit: {
      en: 'Manage Access Config & User Management permissions',
      id: 'Kelola izin Konfigurasi Akses & Manajemen Pengguna',
    },

    chatToolsView: { en: 'Tool Catalog — View', id: 'Katalog Alat — Lihat' },
    chatToolsRequest: { en: 'Tool Catalog — Request', id: 'Katalog Alat — Ajukan' },
    chatFreshpediaView: { en: 'Freshpedia — View', id: 'Freshpedia — Lihat' },
    chatFreshpediaRequest: { en: 'Freshpedia — Request', id: 'Freshpedia — Ajukan' },
    chatStagingTest: { en: 'Staging Preview', id: 'Pratinjau Staging' },
    chatAccessPermissionEdit: {
      en: 'Manage Chat Access permissions',
      id: 'Kelola izin Akses Chat',
    },
  },
  freshpedia: {
    title: { en: 'Freshpedia', id: 'Freshpedia' },
  },
  toolCatalog: {
    title: { en: 'Tool Catalog', id: 'Katalog Alat' },
    toolColumn: { en: 'Tool', id: 'Alat' },
    statusColumn: { en: 'Status', id: 'Status' },
    filterByStatusLabel: { en: 'Filter by status', id: 'Filter berdasarkan status' },
    stagingStatus: { en: 'Staging', id: 'Staging' },
    productionStatus: { en: 'Production', id: 'Produksi' },
  },
  staging: {
    toggleLabel: { en: 'Toggle staging mode', id: 'Alihkan mode staging' },
    bannerLabel: { en: 'STAGING MODE', id: 'MODE STAGING' },
  },
}
